export const images = {
  // logo:require('../../assets/images/logo.png'),
  logo: require("../../../assets/images/logo.jpeg"),
  singUp: require("../../../assets/images/signUp.png"),
  sinIn: require("../../../assets/images/signin.png"),
  otp: require("../../../assets/images/otp.png"),
  camera: require("../../../assets/images/signUpCamera.png"),
  success: require("../../../assets/images/imgSucccess.png"),
  loading: require("../../../assets/loading.json"),
  card: require("../../../assets/images/card.png"),
  cardIcon: require("../../../assets/images/cardIcon.png"),
  account: require("../../../assets/images/account.png"),
  sendMoney: require("../../../assets/images/sendMoney.png"),
  payment: require("../../../assets/images/payment.png"),
  money: require("../../../assets/images/money.png"),
  deposit: require("../../../assets/images/deposit.png"),
  moneyTransfer: require("../../../assets/images/moneyTransfer.png"),
  manageFriend: require("../../../assets/images/manageFriend.png"),
  billPay: require("../../../assets/images/billPay.png"),
  allBudget: require("../../../assets/images/allBudget.png"),
  branchPay: require("../../../assets/images/branchPay.png"),
  transfer: require("../../../assets/images/transfer.png"),
  bra: require("../../../assets/images/bra.png"),
};
